name: Compare Test Results

on:
  push:
    branches:
      - master

jobs:
  compare-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and run tests for main branch
        run: |
          npm install
          #npx jest
          # Save test results to a file (e.g., test-results-main.json)
          npx jest --json --outputFile=test-results-main.json

      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Install dependencies and run tests for current branch
        run: |
          npm install
          #npx jest
          # Save test results to a file (e.g., test-results-current.json)
          npx jest --json --outputFile=test-results-current.json

